on:
    push:
      branches:
        - master

  
  
jobs:
    build:
      runs-on: ubuntu-latest 
     
      steps:
        - name: "testing github actions"
          run: pwd
          
        - name: "Before printing the folder containts"
          run: ls

        - uses: actions/checkout@v3

        - name: "After printing the folder containts"
          run: ls


  
